name:  complex workflow

on: push

jobs:
  ubuntu:
    runs-on: 
    steps: ubuntu-latest
    - run: date
  windows:
    runs-on: windows-latest
    steps:
    - run: date
  macos:
  runs-on: macos-latest
    steps:
    - run: date
  depends:
    needs: [ubuntu, windows, macos]
  runs-on: windows-lates
    steps:
    - run: date
   
