name: Python application

on: [push]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the code
      uses: actions/checkout@v2
    - name: Due Dates
      uses: alexleventer/github-issue-due-dates-action@1.1.0

